version: '3'
services:
  server:
    image: node:8
    volumes:
      - ./server:/opt/api
    working_dir: /opt/api
    command: sh -c "yarn && yarn compile && yarn start"
  client:
    image: nginx:latest
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"

